jdk:
  - openjdk17

before_install:
  - git submodule update --init --recursive
  - if [ ! -d "dashkit/bls-signatures/contrib/relic" ]; then
    git clone https://github.com/relic-toolkit/relic.git dashkit/bls-signatures/contrib/relic;
    fi

install: true  # 使用 JitPack 自带的 Android SDK/NDK

script:
  # 构建 release 版本 AAR
  - ./gradlew clean assembleRelease
