jdk:
  - openjdk17

before_install:
  # 初始化 git 子模块
  - git submodule update --init --recursive
  # 如果 relic 不存在就克隆
  - if [ ! -d "dashkit/bls-signatures/contrib/relic" ]; then
    git clone https://github.com/relic-toolkit/relic.git dashkit/bls-signatures/contrib/relic;
    fi

install:
  - true

script:
  # 构建 release 版本
  - ./gradlew clean :dashkit:bls-signatures:assembleRelease

after_success:
  # 复制生成的 AAR 到 JitPack artifacts
  - mkdir -p $HOME/artifacts
  - cp dashkit/bls-signatures/build/outputs/aar/bls-signatures-release.aar $HOME/artifacts/
