jdk:
  - openjdk17

before_install:
  # 初始化 git 子模块
  - git submodule update --init --recursive
  # 克隆 relic 库
  - if [ ! -d "dashkit/bls-signatures/contrib/relic" ]; then
    git clone https://github.com/relic-toolkit/relic.git dashkit/bls-signatures/contrib/relic;
    fi

install:
  # 可以安装 Android SDK/NDK/CMake，如果需要
  - true

script:
  # 构建所有 library module
  - ./gradlew clean assembleRelease

after_success:
  # 复制 AAR 到 artifacts 目录
  - mkdir -p $HOME/artifacts
  - cp dashkit/library1/build/outputs/aar/library1-release.aar $HOME/artifacts/
  - cp dashkit/library2/build/outputs/aar/library2-release.aar $HOME/artifacts/
